### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by zalexstudios** [DracoR22/ZenithMail#1]
Hi!
In which file should I write API keys?
Thank you!
![Screenshot_1](https://github.com/DracoR22/ZenithMail/assets/2314551/5465ad22-ada7-4848-9d8c-adc44932fc9b)

**Comment by DracoR22** [comment]
Hi, you can place environment variables inside of .env file. I also added a .env.example with all the keys needed for this project

**Comment by zalexstudios** [comment]
Thank you!
